name: Cabinets update by schedule
'on':
  schedule:
    - cron: 0 0 * * *
jobs:
  updating:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: '${{ env.DELAYED_JOB_CHECKOUT_REF }}'
      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install pyrebase
      - name: Run
        run: python scheduleParser.py
    env:
      DELAYED_JOB_CHECKOUT_REF: dbe805b08122670105ca975ef399558b35c78819
      DELAYED_JOB_CHECKOUT_REF_IS_TAG: 'false'
      DELAYED_JOB_WORKFLOW_FILE_PATH: >-
        .github/workflows/scheduledRun-dbe805b08122670105ca975ef399558b35c78819.yml
      DELAYED_JOB_WORKFLOW_UNSCHEDULE_TARGET_BRANCH: main
